plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\User\\.paperclip\\instances\\default\\workspaces\\91af3253-92f3-4039-8601-03e5a1108a7e\\landing\\dist"
publishOrigin = "ui"
commandOrigin = "ui"
base = "C:\\Users\\User\\.paperclip\\instances\\default\\workspaces\\91af3253-92f3-4039-8601-03e5a1108a7e\\landing"
command = "npm run build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]